### ISSUE TITLE
How can I start MobilNetSSD, How to Train?

### ISSUE THREAD

**Issue by MdAshrafulAlam** [djmv/MobilNet_SSD_opencv#1]
I am impressed with your work. I want to start to make another mobilnet SSD. So, how can I improve better than you?

**Comment by sorelyss** [comment]
Hi, the short answer will be: there are a lot of tutorials of how to train SSD mobilnet using the Object Detection API of TensorFlow.

But if you want to try it quickly, you can follow these steps:

1) Clone the [tensorflow/model repository](https://github.com/tensorflow/models) @ anywhere you want.

2) Follow this instructions: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

2.1) Add to ~./bashrc:
```bash
export PYTHONPATH=${PYTHONPATH}:/PATH_TO/tensorflow/models/research:/PATH_TO/tensorflow/models/research/slim 
```
3) Download the checkpoint of a pretrained model (SSD, Mobilnet-SSD, FastRCNN...) [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md).

4) Replace **PATH_TO_BE_CONFIGURED** and **number of classes** at the model.config file.

----------------------------------------
5) Train! 
``` bash
#@/PATH_TO/tensorflow/models/research/
TRAIN_DIR=/PATH_TO_YOUR_TRAIN_FOLDER/ # for example: /home/username/Documents/project/train/
EVAL_DIR=/PATH_TO_YOUR_EVALUATION_FOLDER/
DETECT_DIR=PATH_TO_YOUR_DETECTION_FOLDER/output_inference_graph.pb
PIPELINE_CONFIG_PATH=/PATH_TO_YOUR_CONFIG_FILE/the_name.config

python3 object_detection/train.py --logtostderr \
    --pipeline_config_path=$PIPELINE_CONFIG_PATH \
    --train_dir=$TRAIN_DIR
```
5.1) Watch the training process

    tensorboard --logdir=$TRAIN_DIR

-------------------------------------
References

* For creating your own .record files.
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md
http://www.machinelearninguru.com/deep_learning/tensorflow/basics/tfrecord/tfrecord.html
https://planspace.org/20170323-tfrecords_for_humans/
