### ISSUE TITLE
2 erros 

### ISSUE THREAD

**Issue by DengHaoyang97** [djmv/MobilNet_SSD_opencv#5]
Can please guide me through?

for video input
ModuleNotFoundError: No module named 'numpy'

for image input 

File "sample_img.py", line 109
    print label
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(label)?

**Comment by djmv** [comment]
Yes, put parenthesis in print. 

`print(label)` 

And you have to install numpy library for solve the other error.

`pip install numpy`
