### ISSUE TITLE
A question about detections.shape.

### ISSUE THREAD

**Issue by zgh2022** [djmv/MobilNet_SSD_opencv#6]
I use pytorch to get my model about mobilenet-ssd, and I  transformed my model（.pth）to onnx model,and onnx to caffemodel,
so I get my caffemodel with not using caffe to train. 
But when I use your code to run, I meet a mistake about dim:
In your code, the detections(about net.forward())'s shape is (1, 1, 100, 7), but my shape is (1, 2268 ,3), so I reshape the detections to (1, 1, 972, 3),the code can run ,but It doesn't work well, It can't do anything about confidence and Object location.
So how can I do for the confidence and Object location.
This is my model: https://drive.google.com/drive/folders/1dWObvYe9VRUBJ1D5Teow4Y4M34tJ_6-B?usp=sharing

**Comment by djmv** [comment]
Please, add more information and put code and errors gotted.
